### ISSUE TITLE
Add pt_BR strings

### ISSUE THREAD

**Issue by aevw** [csicar/Ning#14]
Hello devs,

Translated strings below:

[pt_BR](https://github.com/aevw/RD-pt_BR/blob/master/ning.xml)

**Comment by csicar** [comment]
Thanks for the contribution. The translations are now added to Ning.

If you want to see them in action, you can find a nightly build of the APK [here](https://gitlab.com/csicar/Ning/-/jobs/717552982/artifacts/browse)
