### ISSUE TITLE
IP address and MAC address are overlapping each other on the main screen

### ISSUE THREAD

**Issue by dmitriy-ilchenko** [csicar/Ning#21]
Hello. IP address and MAC address are overlapping each other on the main screen.

![Screenshot_20200918_032855_de csicar ning](https://user-images.githubusercontent.com/59684939/93541648-aee9f900-f95f-11ea-95b8-91679b213ad4.jpg)

**Comment by csicar** [comment]
I think I fixed the problem. 
Could you test it out, before I merge it into master?

The APK from the PR can be found here: https://gitlab.com/csicar/Ning/-/jobs/744945549/artifacts/browse

**Comment by dmitriy-ilchenko** [comment]
They are not overlapping, but now they are not on the same line

![Screenshot_20200918_160952_de.csicar.ning.jpg](https://user-images.githubusercontent.com/59684939/93601161-6ff08d80-f9c9-11ea-88aa-15a995b45d8a.jpg)

I suggest aligning textviews vertically to solve this king of problems.

**Comment by csicar** [comment]
Could you post a picture?
Btw: do you have decreased your dpi or increased the font size?

**Comment by csicar** [comment]
The Text views are aligned vertically in the constrained set.. Weird

**Comment by dmitriy-ilchenko** [comment]
No, i did not do anything with dpi or font size. This is the default behavior on my device (Honor 20, Android 10)

**Comment by dmitriy-ilchenko** [comment]
I guess that IP address is above MAC address because autoSizeTextType is set. It moves text to the top if there is not enough space for the whole text. Gravity attribute should solve this problem. Btw, app:autoSizeTextType should be used instead of android:autoSizeTextType. The latest one requires min api 26.

**Comment by csicar** [comment]
Thanks a lot! From what I can tell the alignment is fixed now. Would you mind checking it again?

APK can be found here: https://gitlab.com/csicar/Ning/-/jobs/745952689/artifacts/browse

**Comment by dmitriy-ilchenko** [comment]
Unfortunately, IP address textview is still above MAC address textview a little bit for some reason.

![Screenshot_20200918_233223_de csicar ning](https://user-images.githubusercontent.com/59684939/93642987-ba90fa80-fa07-11ea-9406-7d1f62b5430c.jpg)

But if you replace 
`app:layout_constraintBaseline_toBaselineOf="@+id/ipTextView"`
with 
```
app:layout_constraintTop_toTopOf="@id/ipTextView"
app:layout_constraintBottom_toBottomOf="@id/ipTextView"
```
in MAC address textview, the result will be

![Screenshot_20200918_233419_de csicar ning](https://user-images.githubusercontent.com/59684939/93643178-28d5bd00-fa08-11ea-893d-f9c0e67fafd1.jpg)
