### ISSUE TITLE
Overlapping names

### ISSUE THREAD

**Issue by Porrumentzio** [csicar/Ning#36]
Sometimes IP addresses overlap MAC ones:
![Screenshot_20201229-162209](https://user-images.githubusercontent.com/61913683/103294439-26fd9b80-49f2-11eb-8a57-9c43e9c9c88a.png)

**Comment by csicar** [comment]
https://github.com/csicar/Ning/releases/tag/v1.2.5-alpha-1 should fix this issue

**Comment by csicar** [comment]
I'll assume this is fixed in 1.2.5-alpha-1. If not, please reopen the issue
