### ISSUE TITLE
Crashes every scan

### ISSUE THREAD

**Issue by mbomb007** [csicar/Ning#51]
I get "Ning has stopped" when scanning wlan0. I am not connected to Wi-Fi, and I'm on android 8.1.0.

**Comment by hexxellor** [comment]
I can say that I see this too on Android 11. This appears to simply be that the application starts with wlan0 as the default network to scan but I'm not connected to wireless at the time. 

If I open the menu on the left before attempting a scan I can see that another device is listed, but not wlan0. Selecting the other network first does allow me to scan without the app crashing.

If I don't select some other device/network first though, it does crash immediately.

**Comment by csicar** [comment]
Ning should display a "Network not found" message at the bottom of the screen if you're not connected now (at least at version 2.0.0).

Closing for now; if you can reproduce this on 2.0.0 please reopen the issue.
