### ISSUE TITLE
save available devices per WIFI SSID

### ISSUE THREAD

**Issue by maurerle** [csicar/Ning#7]
saving scanned Wifis and their devices like Fing does would be cool so that you don't need a full rescan before you can scan ports of devices.
But thats just for the far future

**Comment by csicar** [comment]
Scans are already saved. The result are just not yet used. 
I'm working on changing that at the moment :)

**Comment by csicar** [comment]
APK can be found here https://github.com/csicar/Ning/releases/tag/v1.2.3-alpha
